# Basic Information 
title: Seungyeon Lee
position: Ph.D. Student
affiliation: The Ohio State University
email: lee.10029@osu.edu
url: https://yeon-lab.github.io/
keywords: Seungyeon Lee's homepage
description: Seungyeon Lee's homepage.
canonical: https://yeon-lab.github.io/

google_scholar: https://scholar.google.co.kr/citations?user=BFomjFwAAAAJ&hl=en
github_link: https://github.com/yeon-lab/
linkedin: https://www.linkedin.com/in/seungyeon-lee-1621a5191/

avatar: ./assets/img/avatar.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

google_analytics: UA-111540567-4

remote_theme: yaoyao-liu/minimal-light
